[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_summer_transfer_hook = "FbSAuywLK75SUEVhxv1CEHQNqRif4HMuQcEZT1gejbPz"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
